#!/usr/bin/env python3
"""
Brain Semantic Search — Index & Search CLI (Katman 2 + 3)
============================================================
Indexes ~/brain/ files into PostgreSQL (pgvector) for semantic search.
Supports: markdown (.md), PDF (.pdf), text (.txt), transcripts (.srt/.vtt).
Uses Ollama nomic-embed-text (768-dim) + PyMuPDF4LLM for PDF extraction.
Each chunk is tagged with agent_profile for per-agent isolation.

Usage:
    python index_brain.py --rebuild                 # Full re-index all files
    python index_brain.py --update                  # Only index changed files (hash-based)
    python index_brain.py --status                  # Show index statistics
    python index_brain.py --search "query"          # Semantic search (shared only)
    python index_brain.py --search "query" --profile maya     # Search maya + shared
    python index_brain.py --search "query" --profile all      # Search everything
    python index_brain.py --search "query" --top 10 --show-content

Requirements (all in Honcho venv):
    psycopg (v3), httpx, pymupdf4llm, pymupdf
    ~/honcho/.venv/bin/python
"""

import argparse
import hashlib
import re
import sys
import time
from pathlib import Path
from typing import List, Dict, Tuple, Optional

import psycopg
import httpx

# ─── Config ───────────────────────────────────────────────────────────────────

import os as _os
BRAIN_PATH = Path(_os.path.expanduser("~/brain"))
# DB_URI: Update 'user' to match your PostgreSQL username (usually your macOS username)
DB_URI = f"host=localhost port=5432 dbname=honcho user={_os.environ.get('USER', _os.getlogin())}"
OLLAMA_EMBED_URL = "http://localhost:11434/api/embeddings"
EMBED_MODEL = "nomic-embed-text"
EMBED_DIM = 768

# Chunking: markdown header-based + size guard
MIN_CHUNK_CHARS = 80      # Skip tiny chunks (e.g., just a header line)
MAX_CHUNK_CHARS = 1500    # Split very long sections into multiple chunks
OVERLAP_CHARS = 150       # Overlap between adjacent sub-chunks within a section

# File types we support
SUPPORTED_EXTENSIONS = {".md", ".pdf", ".txt", ".srt", ".vtt"}

# References sources directory — where per-agent PDFs/transcripts live
SOURCES_BASE = "references/sources"

# ─── Database Operations ──────────────────────────────────────────────────────

def get_conn():
    return psycopg.connect(DB_URI)


def init_table(conn):
    """Create brain_documents table if not exists (idempotent)."""
    with conn.cursor() as cur:
        cur.execute("""
            CREATE TABLE IF NOT EXISTS brain_documents (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                file_path TEXT NOT NULL,
                file_hash TEXT NOT NULL,
                chunk_index INTEGER NOT NULL,
                content TEXT NOT NULL,
                embedding vector(768),
                agent_profile TEXT NOT NULL DEFAULT 'shared',
                source_type TEXT NOT NULL DEFAULT 'markdown',
                page_num INTEGER DEFAULT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                UNIQUE(file_path, chunk_index)
            );
        """)
        cur.execute("""
            CREATE INDEX IF NOT EXISTS ix_brain_documents_file_path
            ON brain_documents USING btree (file_path);
        """)
        cur.execute("""
            CREATE INDEX IF NOT EXISTS ix_brain_documents_file_hash
            ON brain_documents USING btree (file_hash);
        """)
        cur.execute("""
            CREATE INDEX IF NOT EXISTS ix_brain_documents_agent_profile
            ON brain_documents USING btree (agent_profile);
        """)
        cur.execute("""
            CREATE INDEX IF NOT EXISTS ix_brain_documents_embedding_hnsw
            ON brain_documents USING hnsw (embedding vector_cosine_ops)
            WITH (m = 16, ef_construction = 64);
        """)
    conn.commit()


def drop_all_chunks(conn, file_path: str):
    with conn.cursor() as cur:
        cur.execute("DELETE FROM brain_documents WHERE file_path = %s", (file_path,))


def get_indexed_files(conn) -> Dict[str, str]:
    with conn.cursor() as cur:
        cur.execute(
            "SELECT file_path, MAX(file_hash) as hash FROM brain_documents "
            "GROUP BY file_path"
        )
        return {row[0]: row[1] for row in cur.fetchall()}


def insert_chunk(conn, file_path: str, file_hash: str, chunk_index: int,
                 content: str, embedding: List[float], 
                 agent_profile: str = "shared", source_type: str = "markdown",
                 page_num: Optional[int] = None):
    emb_str = "[" + ",".join(f"{x:.8f}" for x in embedding) + "]"
    with conn.cursor() as cur:
        cur.execute(
            """INSERT INTO brain_documents
               (file_path, file_hash, chunk_index, content, embedding,
                agent_profile, source_type, page_num)
               VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
               ON CONFLICT (file_path, chunk_index)
               DO UPDATE SET file_hash = EXCLUDED.file_hash,
                             content = EXCLUDED.content,
                             embedding = EXCLUDED.embedding,
                             agent_profile = EXCLUDED.agent_profile,
                             source_type = EXCLUDED.source_type,
                             page_num = EXCLUDED.page_num,
                             updated_at = now()""",
            (file_path, file_hash, chunk_index, content, emb_str,
             agent_profile, source_type, page_num)
        )


# ─── Embedding ───────────────────────────────────────────────────────────────

def get_embedding(text: str) -> List[float]:
    text = text[:32000]
    resp = httpx.post(OLLAMA_EMBED_URL, json={
        "model": EMBED_MODEL,
        "prompt": text,
    }, timeout=60)
    resp.raise_for_status()
    return resp.json()["embedding"]


# ─── Content Extraction ───────────────────────────────────────────────────────

def extract_content(fpath: Path) -> Tuple[List[Dict], str, str]:
    """
    Extract content from any supported file type.
    Returns: (chunks_list, agent_profile, source_type)
    
    chunks_list: List of {"content": str, "page_num": int|None}
    agent_profile: derived from path (shared/ayda/alex/sage/maya/<custom>)
    source_type: markdown/pdf/txt/transcript
    """
    suffix = fpath.suffix.lower()

    if suffix == ".md":
        content = fpath.read_text(encoding="utf-8", errors="replace")
        raw_chunks = chunk_markdown(content)
        chunks = [{"content": text, "page_num": None} for _, text in raw_chunks]
        return (chunks, _derive_profile(fpath), "markdown")

    elif suffix == ".pdf":
        return extract_pdf(fpath)

    elif suffix == ".txt":
        content = fpath.read_text(encoding="utf-8", errors="replace")
        raw_chunks = chunk_markdown(content)
        chunks = [{"content": text, "page_num": None} for _, text in raw_chunks]
        return (chunks, _derive_profile(fpath), "txt")

    elif suffix in (".srt", ".vtt"):
        content = extract_transcript(fpath)
        raw_chunks = chunk_markdown(content)
        chunks = [{"content": text, "page_num": None} for _, text in raw_chunks]
        return (chunks, _derive_profile(fpath), "transcript")

    else:
        return ([], "shared", "unknown")


def _derive_profile(fpath: Path) -> str:
    """
    Derive agent_profile from file path.
    - Files under references/sources/<agent-name>/ → agent-name
    - Files under references/sources/shared/ → shared
    - All other files → shared (brain markdown etc.)
    """
    rel = fpath.relative_to(BRAIN_PATH)
    parts = rel.parts

    # Check if path starts with references/sources/
    if len(parts) >= 3 and parts[0] == "references" and parts[1] == "sources":
        profile = parts[2]  # e.g. "maya", "ayda", "shared"
        return profile

    return "shared"


def extract_pdf(fpath: Path) -> Tuple[List[Dict], str, str]:
    """
    Extract PDF using PyMuPDF4LLM → markdown.
    Chunks are page-aware: each chunk knows its page number.
    """
    import pymupdf4llm

    # Convert PDF to markdown — returns a single markdown string
    md_text = pymupdf4llm.to_markdown(str(fpath))

    # Also get per-page text for page numbering
    import pymupdf
    doc = pymupdf.open(str(fpath))
    total_pages = len(doc)

    # Strategy: Split the full markdown by headers (normal chunking),
    # but also track which page each chunk belongs to.
    # PyMuPDF4LLM embeds page info in the markdown as headers.
    # We'll do header-based chunking, then map chunks to pages by
    # looking up the page markers that PyMuPDF4LLM inserts.

    # PyMuPDF4LLM outputs markdown with page separators.
    # We'll use a hybrid approach: chunk by headers, then for each chunk
    # try to determine the page from the surrounding context.

    # Simpler approach: also get per-page text, chunk each page separately,
    # then combine with the markdown chunks for better context.

    chunks = chunk_pdf_with_pages(md_text, doc)
    doc.close()

    return (chunks, _derive_profile(fpath), "pdf")


def chunk_pdf_with_pages(md_text: str, doc) -> List[Dict]:
    """
    Chunk PDF markdown while tracking page numbers.
    
    PyMuPDF4LLM outputs markdown. We split by headers like chunk_markdown(),
    but for each chunk we also determine which page(s) it came from.
    
    Strategy: Split markdown into sections by headers, then for each section
    try to find a page reference. If no page reference found, use the
    per-page text matching to determine the page.
    """
    # First, try to extract page markers from the markdown
    # PyMuPDF4LLM typically doesn't embed page numbers directly,
    # so we'll do per-page extraction as a fallback.

    # Get per-page text for page mapping
    page_texts = []
    for i, page in enumerate(doc):
        page_text = page.get_text()
        page_texts.append(page_text)

    # Chunk the full markdown by headers
    header_chunks = chunk_markdown(md_text)

    # For each chunk, try to determine the page by matching
    # chunk content against page text
    chunks_with_pages = []
    for chunk_idx, chunk_text in header_chunks:
        # Try to find which page this chunk came from
        page_num = _find_page_for_chunk(chunk_text, page_texts)
        chunks_with_pages.append({
            "content": chunk_text,
            "page_num": page_num,
        })

    # Fallback: if no pages found at all, assign pages sequentially
    if all(c["page_num"] is None for c in chunks_with_pages):
        # Divide chunks roughly equally across pages
        num_chunks = len(chunks_with_pages)
        for i, c in enumerate(chunks_with_pages):
            # Rough proportional assignment
            page = min(int(i * len(page_texts) / num_chunks) + 1, len(page_texts))
            c["page_num"] = page

    return chunks_with_pages


def _find_page_for_chunk(chunk_text: str, page_texts: List[str]) -> Optional[int]:
    """
    Find which page a chunk most likely came from by matching text.
    Uses first meaningful sentence as fingerprint.
    """
    # Extract a fingerprint: first 100 non-whitespace chars
    fingerprint = re.sub(r'\s+', ' ', chunk_text)[:100].strip()
    if len(fingerprint) < 20:
        return None

    best_page = None
    best_score = 0

    for i, page_text in enumerate(page_texts):
        # Normalize page text for matching
        normalized_page = re.sub(r'\s+', ' ', page_text)
        # Check if fingerprint appears in this page
        if fingerprint[:50] in normalized_page:
            return i + 1  # Pages are 1-indexed
        # Fuzzy: count matching words
        fingerprint_words = set(fingerprint.split())
        page_words = set(normalized_page.split())
        overlap = len(fingerprint_words & page_words)
        if overlap > best_score:
            best_score = overlap
            best_page = i + 1

    # Only return if we have a reasonable match
    if best_score > 5:
        return best_page
    return None


def extract_transcript(fpath: Path) -> str:
    """
    Extract plain text from SRT or VTT subtitle/transcript files.
    Strips timestamps and sequence numbers, returns clean text.
    """
    raw = fpath.read_text(encoding="utf-8", errors="replace")

    if fpath.suffix.lower() == ".srt":
        # SRT format: sequence number, timestamp line, text lines, blank line
        lines = raw.split("\n")
        text_lines = []
        for line in lines:
            line = line.strip()
            # Skip sequence numbers (pure digits)
            if line.isdigit():
                continue
            # Skip timestamp lines (contains -->)
            if "-->" in line:
                continue
            # Skip empty lines
            if not line:
                continue
            text_lines.append(line)
        return "\n\n".join(text_lines)

    elif fpath.suffix.lower() == ".vtt":
        # VTT format: WEBVTT header, timestamp lines, text lines
        lines = raw.split("\n")
        text_lines = []
        for line in lines:
            line = line.strip()
            # Skip WEBVTT header
            if line.startswith("WEBVTT"):
                continue
            # Skip timestamp lines
            if "-->" in line:
                continue
            # Skip empty lines
            if not line:
                continue
            # Skip cue identifiers (lines that look like numbers or timestamps)
            if re.match(r'^[\d:.\-]+$', line):
                continue
            text_lines.append(line)
        return "\n\n".join(text_lines)

    return raw


# ─── Chunking ─────────────────────────────────────────────────────────────────

def chunk_markdown(content: str) -> List[Tuple[int, str]]:
    """
    Split markdown by headers (#, ##, ###, etc.).
    Returns list of (chunk_index, chunk_text).
    """
    header_pattern = re.compile(r'^(#{1,6}\s+.+)$', re.MULTILINE)
    sections: List[Tuple[str, str]] = []

    matches = list(header_pattern.finditer(content))
    if not matches:
        sections.append(("", content))
    else:
        pre_header = content[:matches[0].start()].strip()
        if len(pre_header) > MIN_CHUNK_CHARS:
            sections.append(("", pre_header))

        for i, match in enumerate(matches):
            header_line = match.group(1)
            start = match.start()
            end = matches[i + 1].start() if i + 1 < len(matches) else len(content)
            body = content[start:end].strip()
            if len(body) >= MIN_CHUNK_CHARS:
                sections.append((header_line, body))

    chunks: List[str] = []
    for header, body in sections:
        if len(body) <= MAX_CHUNK_CHARS:
            chunks.append(body)
        else:
            sub_chunks = split_with_overlap(body, MAX_CHUNK_CHARS, OVERLAP_CHARS)
            chunks.extend(sub_chunks)

    return [(i, chunk) for i, chunk in enumerate(chunks)]


def split_with_overlap(text: str, max_size: int, overlap: int) -> List[str]:
    chunks = []
    start = 0
    while start < len(text):
        end = start + max_size
        if end >= len(text):
            chunks.append(text[start:])
            break
        para_break = text.rfind('\n\n', start, end)
        if para_break > start + max_size // 2:
            end = para_break + 2
        else:
            sent_break = text.rfind('. ', start, end)
            if sent_break > start + max_size // 2:
                end = sent_break + 2
        chunks.append(text[start:end])
        start = end - overlap
    return chunks


# ─── File Discovery ───────────────────────────────────────────────────────────

def find_source_files() -> List[Path]:
    """Find all supported files in brain, excluding .git and scripts."""
    files = []
    for f in BRAIN_PATH.rglob("*"):
        if f.is_dir():
            continue
        rel = f.relative_to(BRAIN_PATH)
        if any(part == ".git" for part in rel.parts):
            continue
        if rel.parts[0] == "scripts":
            continue
        if rel.name == "AGENTS.md":
            continue
        if f.suffix.lower() in SUPPORTED_EXTENSIONS:
            files.append(f)
    return sorted(files)


def file_hash(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def relative_path(path: Path) -> str:
    return str(path.relative_to(BRAIN_PATH))


# ─── Index Operations ─────────────────────────────────────────────────────────

def index_file(conn, fpath: Path, rel_path: str, fhash: str) -> int:
    """Index a single file. Returns number of chunks indexed."""
    chunks_list, agent_profile, source_type = extract_content(fpath)
    if not chunks_list:
        return 0

    drop_all_chunks(conn, rel_path)

    # All chunk formats are now List[Dict] with {"content", "page_num"}
    for chunk_idx, chunk_dict in enumerate(chunks_list):
        chunk_text = chunk_dict["content"]
        page_num = chunk_dict.get("page_num")
        embedding = get_embedding(chunk_text)
        insert_chunk(conn, rel_path, fhash, chunk_idx, chunk_text,
                    embedding, agent_profile, source_type, page_num)

    return len(chunks_list)


def rebuild_index(conn, profile: Optional[str] = None):
    """Full re-index: drop everything, re-index all files."""
    files = find_source_files()
    print(f"Rebuilding index for {len(files)} files...")

    with conn.cursor() as cur:
        if profile:
            cur.execute("DELETE FROM brain_documents WHERE agent_profile = %s", (profile,))
        else:
            cur.execute("TRUNCATE brain_documents RESTART IDENTITY;")
    conn.commit()

    total_chunks = 0
    start_time = time.time()

    for i, fpath in enumerate(files, 1):
        rel = relative_path(fpath)
        fhash = file_hash(fpath)
        n = index_file(conn, fpath, rel, fhash)
        total_chunks += n
        elapsed = time.time() - start_time
        print(f"  [{i}/{len(files)}] {rel} — {n} chunks ({elapsed:.1f}s)")

    conn.commit()
    elapsed = time.time() - start_time
    print(f"\n* Rebuilt: {len(files)} files, {total_chunks} chunks in {elapsed:.1f}s")


def update_index(conn):
    """Only index changed files (hash-based)."""
    files = find_source_files()
    indexed = get_indexed_files(conn)

    new_files = []
    changed_files = []
    deleted_files = []

    current_paths = set()
    for fpath in files:
        rel = relative_path(fpath)
        current_paths.add(rel)
        fhash = file_hash(fpath)
        if rel not in indexed:
            new_files.append((fpath, rel, fhash))
        elif indexed[rel] != fhash:
            changed_files.append((fpath, rel, fhash))

    for rel in indexed:
        if rel not in current_paths:
            deleted_files.append(rel)

    if not new_files and not changed_files and not deleted_files:
        print("* Index is up to date. No changes needed.")
        return

    total_ops = 0
    start_time = time.time()

    for fpath, rel, fhash in new_files:
        n = index_file(conn, fpath, rel, fhash)
        total_ops += n
        if n > 0:
            st = fpath.suffix.lower()
            prof = _derive_profile(fpath)
            print(f"  [NEW] {rel} — {n} chunks ({st}, profile={prof})")

    for fpath, rel, fhash in changed_files:
        n = index_file(conn, fpath, rel, fhash)
        total_ops += n
        print(f"  [UPD] {rel} — {n} chunks")

    for rel in deleted_files:
        drop_all_chunks(conn, rel)
        print(f"  [DEL] {rel}")

    conn.commit()
    elapsed = time.time() - start_time
    print(f"\n* Updated: {len(new_files)} new, {len(changed_files)} changed, "
          f"{len(deleted_files)} deleted — {total_ops} chunks in {elapsed:.1f}s")


def show_status(conn):
    """Show index statistics."""
    with conn.cursor() as cur:
        cur.execute("SELECT COUNT(*) FROM brain_documents;")
        total = cur.fetchone()[0]

        cur.execute("SELECT COUNT(DISTINCT file_path) FROM brain_documents;")
        files_count = cur.fetchone()[0]

        cur.execute("""
            SELECT agent_profile, COUNT(*) as chunks, COUNT(DISTINCT file_path) as files
            FROM brain_documents
            GROUP BY agent_profile
            ORDER BY chunks DESC;
        """)
        profile_stats = cur.fetchall()

        cur.execute("""
            SELECT source_type, COUNT(*) as chunks
            FROM brain_documents
            GROUP BY source_type
            ORDER BY chunks DESC;
        """)
        type_stats = cur.fetchall()

        cur.execute("""
            SELECT file_path, COUNT(*) as chunks, agent_profile, source_type
            FROM brain_documents
            GROUP BY file_path, agent_profile, source_type
            ORDER BY chunks DESC
            LIMIT 10;
        """)
        top_files = cur.fetchall()

        cur.execute("""
            SELECT AVG(length(content)) as avg_chunk_size,
                   MIN(length(content)) as min_chunk_size,
                   MAX(length(content)) as max_chunk_size
            FROM brain_documents;
        """)
        sizes = cur.fetchone()

        cur.execute("SELECT COUNT(*) FROM brain_documents WHERE embedding IS NULL;")
        null_emb = cur.fetchone()[0]

        cur.execute("""
            SELECT COUNT(DISTINCT page_num) 
            FROM brain_documents 
            WHERE page_num IS NOT NULL;
        """)
        pages_indexed = cur.fetchone()[0]

    print(f"=== Brain Search Index Status ===")
    print(f"  Total chunks:      {total}")
    print(f"  Files indexed:     {files_count}")
    print(f"  Pages indexed:     {pages_indexed} (PDF page refs)")
    print(f"  Null embeddings:   {null_emb}")
    if sizes and sizes[0] is not None:
        print(f"  Chunk size:        avg={sizes[0]:.0f}, min={sizes[1]}, max={sizes[2]} chars")

    if profile_stats:
        print(f"\n  -- By Agent Profile --")
        for prof, chunks, files in profile_stats:
            print(f"    {prof:15s} {chunks:5d} chunks, {files:3d} files")

    if type_stats:
        print(f"\n  -- By Source Type --")
        for st, chunks in type_stats:
            print(f"    {st:15s} {chunks:5d} chunks")

    if top_files:
        print(f"\n  -- Top 10 files by chunk count --")
        for path, count, prof, st in top_files:
            print(f"    {count:3d} chunks [{prof}/{st}] {path}")


# ─── Search ───────────────────────────────────────────────────────────────────

def search_brain(conn, query: str, top_k: int = 5,
                 show_content: bool = False,
                 profile: str = "shared") -> List[Dict]:
    """
    Semantic search across brain documents.
    profile: 'shared' (default), or agent name, or 'all'
    """
    query_embedding = get_embedding(query)
    emb_str = "[" + ",".join(f"{x:.8f}" for x in query_embedding) + "]"

    if profile == "all":
        sql = """
            SELECT file_path, chunk_index, content,
                   agent_profile, source_type, page_num,
                   1 - (embedding <=> %s::vector) as similarity
            FROM brain_documents
            WHERE embedding IS NOT NULL
            ORDER BY embedding <=> %s::vector
            LIMIT %s;
        """
        params = (emb_str, emb_str, top_k)
    elif profile == "shared":
        sql = """
            SELECT file_path, chunk_index, content,
                   agent_profile, source_type, page_num,
                   1 - (embedding <=> %s::vector) as similarity
            FROM brain_documents
            WHERE embedding IS NOT NULL AND agent_profile = 'shared'
            ORDER BY embedding <=> %s::vector
            LIMIT %s;
        """
        params = (emb_str, emb_str, top_k)
    else:
            # Agent-specific: include both the agent's files AND shared
            sql = f"""\
                SELECT file_path, chunk_index, content,
                       agent_profile, source_type, page_num,
                       1 - (embedding <=> %s::vector) as similarity
                FROM brain_documents
                WHERE embedding IS NOT NULL 
                  AND agent_profile IN ({profile!r}, 'shared')
                ORDER BY embedding <=> %s::vector
                LIMIT %s;
            """
            params = (emb_str, emb_str, top_k)

    with conn.cursor() as cur:
        cur.execute(sql, params)
        results = []
        for row in cur.fetchall():
            results.append({
                "file_path": row[0],
                "chunk_index": row[1],
                "content": row[2],
                "agent_profile": row[3],
                "source_type": row[4],
                "page_num": row[5],
                "similarity": float(row[6]),
            })

    return results


def format_search_results(results: List[Dict], query: str, show_content: bool):
    print(f'=== Semantic Search: "{query}" ===')
    print(f"  {len(results)} results\n")

    for i, r in enumerate(results, 1):
        score_pct = r["similarity"] * 100
        # Build citation line
        citation_parts = [f"profile={r['agent_profile']}", f"type={r['source_type']}"]
        if r["page_num"] is not None:
            citation_parts.append(f"pg.{r['page_num']}")
        citation = ", ".join(citation_parts)

        print(f"  [{i}] {r['file_path']} (chunk {r['chunk_index']})")
        print(f"      Similarity: {score_pct:.1f}%  [{citation}]")
        if show_content:
            preview = r["content"][:500]
            if len(r["content"]) > 500:
                preview += "..."
            print(f"      +--------------------------------------------")
            for line in preview.split("\n"):
                print(f"      | {line}")
            print(f"      +--------------------------------------------")
        print()


# ─── CLI ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Brain Semantic Search — Index & Search CLI (Katman 2+3)"
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--rebuild", action="store_true",
                       help="Full re-index (drops everything, re-inserts all)")
    group.add_argument("--update", action="store_true",
                       help="Only index changed files (hash-based)")
    group.add_argument("--status", action="store_true",
                       help="Show index statistics")
    group.add_argument("--search", type=str, metavar="QUERY",
                       help="Semantic search query")

    parser.add_argument("--top", type=int, default=5,
                        help="Number of results to return (default: 5)")
    parser.add_argument("--show-content", action="store_true",
                        help="Print chunk content in search results")
    parser.add_argument("--profile", type=str, default="shared",
                        help="Agent profile for search: 'shared' (default), "
                             "agent name (e.g. 'maya'), or 'all'")

    args = parser.parse_args()
    conn = get_conn()
    init_table(conn)

    try:
        if args.rebuild:
            rebuild_index(conn)
        elif args.update:
            update_index(conn)
        elif args.status:
            show_status(conn)
        elif args.search:
            results = search_brain(conn, args.search, args.top,
                                   args.show_content, args.profile)
            format_search_results(results, args.search, args.show_content)
    finally:
        conn.close()


if __name__ == "__main__":
    main()
